int valida_nome(char *str);
int valida_idade(int);
int valida_sexo(char *str);
int valida_email(char *email);
int valida_peso(float);
int valida_altura(float);
int valida_atividade_fisica(char *str);
int valida_cpf(char *cpf);
int calcula_idade(char* data_nascimento);
int valida_data(char* data_nascimento);